Fix stat clients in tests
The `uds` procotol expects a working socket on
`/var/run/datadog/dsd.socket`.

We don't have it during tests and got:

> Error: Socket not created properly. Check previous errors for details.
> Error: connect -2

Outside production we now default to udp on localhost, which does not
fail.